### ISSUE TITLE
In Dave Gnuken 1.0, the logs are saved to $HOME

### ISSUE THREAD

**Issue by keithbowes** [davidjoffe/dave_gnukem#120]
Yeah, my home directory is littered with files like ~/.old0, ~/.old1, ~/.old2, instead of e.g. ~/.gnukem/logs/DaveGnukem.old{0,1,2}.  (Maybe this has fixed in Git (though, I can't see anything about it browsing through the commits), but I certainly don't want to spend the energy installing the development libraries for an ancient version of SDL to test it.)

**Comment by davidjoffe** [comment]
Gosh, you're right, thanks for reporting this - no it hasn't been fixed yet.

I am not about that log system in general with the old log files, I don't really feel it's worth rotating the logs and keeping old ones anyway, so might just simplify that.

**Comment by davidjoffe** [comment]
PS sdl2 didn't exist when this project was created, sdl1.2 came out as brand new thing somewhere midway through this project, and it would take a lot of my time and energy to re-code the entire thing in sdl2, so considering I'm doing this for free you can drop the snark about it being an "ancient" version of sdl.

**Comment by davidjoffe** [comment]
I have committed what should fix this:

https://github.com/davidjoffe/dave_gnukem/commit/1240c7638c3e7b888bce695d8b8f654fc76183e7

**Comment by davidjoffe** [comment]
PS on most platforms you should be able to just:

apt-get install libsdl1.2-dev

apt-get install libsdl-mixer1.2-dev

to install the dependencies.

I tested the fix quickly now on Linux and Mac.
