### ISSUE TITLE
Dave Gnukem packaged for Arch Linux in the AUR

### ISSUE THREAD

**Issue by caltlgin** [davidjoffe/dave_gnukem#124]
I have added Dave Gnukem into the Arch Linux AUR. I thought you might want to add a link to the Readme next to the opensuse link.

https://aur.archlinux.org/packages/dave_gnukem/

**Comment by davidjoffe** [comment]
:) This is wonderful, thank you! I added a link to the readme

**Comment by caltlgin** [comment]
Awesome. Thanks for making Dave Gnukem. :)
