### ISSUE TITLE
Fault on Pi4

### ISSUE THREAD

**Issue by Exarkuniv** [davidjoffe/dave_gnukem#129]
Raspberry Pi4
PRETTY_NAME="Raspbian GNU/Linux 10 (buster)"
NAME="Raspbian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=raspbian
ID_LIKE=debian

i got it to build just fine but when i go to start it. i just get a Segmentation fault. not sure if it will work since i dont have a desktop. just commend line

**Comment by davidjoffe** [comment]
Thx for the feedback! Did you also 'git clone' the data folder relative to where you are running the binary from? I think that may happen if the data folder isn't found.

(There are two repos, the data is in a separate repo)

I have compiled and run on my own Pi4 and didn't have any problem, eg https://twitter.com/d_joffe/status/1274379877953736704/photo/1

**Comment by Exarkuniv** [comment]
i did do that, but one thing i did not relize is it might not run since i dont have a desktop since im running Retropie and they have the desktop turned off. 
but i did find a command that might work. that i used to get OpenRA to run

**Comment by Exarkuniv** [comment]
yes that did it
i needed to run `sudo xinit ./davegnukem'
and that got it working for me. 
sorry about all this. im still learning how to get things working on my Pi
