### ISSUE TITLE
MMGR - The Memory Manager is non-free

### ISSUE THREAD

**Issue by bgermann** [davidjoffe/dave_gnukem#134]
MMGR - The Memory Manager that is contained in this project is non-free as it does not allow changing the code or redistributing a changed version. This is incompatible with GPL. Please replace or remove it or make it possible to compile your program without it.

The current version available at https://www.paulnettle.com/ has a different license which is also non-free because it has the clause "You may not use this software to directly or indirectly cause harm to others."

**Comment by davidjoffe** [comment]
Hi, hm, thanks! I'm not even sure we're even actually using it or using it very littel (someone else added it years ago), I'll check this closer as soon as I get a chance! Am very busy right now but will check on this soon. I'm sure it shouldn't be difficult to remove it. I don't think I ever used it in my own parts of the code so it's either very limited in use or possibly almost nothing using it ... .

**Comment by bgermann** [comment]
There is already a pull request removing this:  #137

**Comment by davidjoffe** [comment]
This pull request has been merged - thanks so much! I'll try help respond quick to any further contributions
