### ISSUE TITLE
Linux segfault on exit? (on Debian7 test system)

### ISSUE THREAD

**Issue by davidjoffe** [davidjoffe/dave_gnukem#43]

**Comment by pocak100** [comment]
Hi.

I, too, have seen these segfaults on Arch Linux 32.

[Here's what valgrind says about it.](https://gist.github.com/pocak100/b4548c66ef81298c40244832500985ca)

It looks like a case of the [static initialization order fiasco](https://isocpp.org/wiki/faq/ctors#static-init-order), except at de-initialization time.


After `main()` ends, static (global) objects are destructed. In the case of `CMenu`, the destructor uses the `SYS_Debug` macro, which calls `_SetFileAndLine`, which sets the global `std::string g_sFile`. However, at that point, `g_sFile` may have already been destructed and deallocated, so the assignment segfaults.

```c++
CMenu::~CMenu()
{
	SYS_Debug ( "CMenu::~CMenu (%s)\n", idstring );
...
```
```c++
#define SYS_Debug (_SetFileAndLine ( __FILE__, __LINE__ ),false)?(void)the_void:_SYS_Debug
```
```c++
std::string g_sFile;
static int	g_nLine = 0;

void _SetFileAndLine ( const char *filename, const int linenum )
{
	// [dj2017-06-20] Make a copy of the passed-in filename string rather than keep pointer to it (in case caller deletes string, then this would crash)
	g_sFile = "";
	if (filename!=NULL)
		g_sFile = filename;
	g_nLine = linenum;
}
```

In my opinion, the cleanest way to resolve this is to change `SYS_Debug` to a variadic macro, so `_SetFileAndLine` isn't needed anymore:
```c++
#define SYS_Debug(...) (_SYS_Debug(__FILE__, __LINE__, __VA_ARGS__))
```
The caveat is that variadic macros have only been standardized in c++11, thus, applying this fix effectively bumps up the project's compiler requirements, so I thought I'd ask first. If c++11 is fine, I'll bang out a pull request. If you wish to stick to c++98, well, there are other solutions.

**Comment by learn-more** [comment]
Converting `g_sFile` into a (zero-initialized) `const char*` should also fix this?
the `__FILE__` macro according to https://gcc.gnu.org/onlinedocs/cpp/Standard-Predefined-Macros.html:
> This macro expands to the name of the current input file, in the form of a C string constant.

which _should_ make it safe enough to use like that?
